2025-03-31 15:14:27,827 INFO    MainThread:12220 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-31 15:14:27,827 INFO    MainThread:12220 [wandb_setup.py:_flush():67] Configure stats pid to 12220
2025-03-31 15:14:27,827 INFO    MainThread:12220 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Morten\.config\wandb\settings
2025-03-31 15:14:27,827 INFO    MainThread:12220 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Morten\Desktop\P6\wandb\settings
2025-03-31 15:14:27,827 INFO    MainThread:12220 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-31 15:14:27,828 INFO    MainThread:12220 [wandb_init.py:setup_run_log_directory():647] Logging user logs to C:\Users\Morten\Desktop\P6\wandb\run-20250331_151427-7k0pimbj\logs\debug.log
2025-03-31 15:14:27,830 INFO    MainThread:12220 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to C:\Users\Morten\Desktop\P6\wandb\run-20250331_151427-7k0pimbj\logs\debug-internal.log
2025-03-31 15:14:27,880 INFO    MainThread:12220 [wandb_init.py:init():761] calling init triggers
2025-03-31 15:14:27,880 INFO    MainThread:12220 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'rollouts': 1000, 'percentile': 0.7, 'discount_factor': 0.99, 'learning_rate': 0.01, 'learning_rate_scheduler': None, 'learning_rate_scheduler_kwargs': {}, 'state_preprocessor': None, 'state_preprocessor_kwargs': {}, 'random_timesteps': 0, 'learning_starts': 100, 'rewards_shaper': None, 'mixed_precision': False, 'experiment': {'directory': 'Mortens_Folder/Mortens_SKRL/CartPole/runs', 'experiment_name': '', 'write_interval': 1000, 'checkpoint_interval': 5000, 'store_separately': False, 'wandb': True, 'wandb_kwargs': {'entity': 'urkanin-aalborg-universitet', 'project': 'P6'}}, 'timesteps': 100000, 'headless': True, 'disable_progressbar': False, 'close_environment_at_exit': True, 'environment_info': 'episode', 'stochastic_evaluation': False, 'policy': {'linear_layer_1': Linear(in_features=4, out_features=64, bias=True), 'linear_layer_2': Linear(in_features=64, out_features=64, bias=True), 'output_layer': Linear(in_features=64, out_features=2, bias=True)}, '_wandb': {}}
2025-03-31 15:14:27,880 INFO    MainThread:12220 [wandb_init.py:init():784] starting backend
2025-03-31 15:14:27,880 INFO    MainThread:12220 [wandb_init.py:init():788] sending inform_init request
2025-03-31 15:14:27,908 INFO    MainThread:12220 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-03-31 15:14:27,908 INFO    MainThread:12220 [wandb_init.py:init():798] backend started and connected
2025-03-31 15:14:27,911 INFO    MainThread:12220 [wandb_init.py:init():891] updated telemetry
2025-03-31 15:14:27,977 INFO    MainThread:12220 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-31 15:14:28,753 INFO    MainThread:12220 [wandb_init.py:init():990] starting run threads in backend
2025-03-31 15:14:29,130 INFO    MainThread:12220 [wandb_run.py:_console_start():2375] atexit reg
2025-03-31 15:14:29,132 INFO    MainThread:12220 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-31 15:14:29,132 INFO    MainThread:12220 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-31 15:14:29,132 INFO    MainThread:12220 [wandb_run.py:_redirect():2315] Redirects installed.
2025-03-31 15:14:29,176 INFO    MainThread:12220 [wandb_init.py:init():1032] run started, returning control to user process
2025-03-31 15:14:29,176 INFO    MainThread:12220 [wandb_run.py:_tensorboard_callback():1449] tensorboard callback: Mortens_Folder/Mortens_SKRL/CartPole/runs\25-03-31_15-14-14-027765_CEM, True
2025-03-31 15:15:51,199 INFO    MsgRouterThr:12220 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
2025-03-31 15:15:52,585 ERROR   MainThread:12220 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "C:\Users\Morten\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "C:\Users\Morten\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Morten\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Morten\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Users\Morten\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Users\Morten\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Users\Morten\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Morten\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Morten\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Morten\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Morten\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-31 15:15:52,593 ERROR   MainThread:12220 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "C:\Users\Morten\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "C:\Users\Morten\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Morten\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Morten\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Users\Morten\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Users\Morten\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Users\Morten\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Morten\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Morten\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Morten\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Morten\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
